name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've thought about.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which area of ClawShield does this relate to?
      options:
        - Proxy / Request Interceptor
        - Agent Firewall / Rule Engine
        - Skill Analyzer
        - Prompt Injection Detection
        - Authentication / JWT
        - WebSocket
        - API
        - CLI
        - Dashboard
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Important - affects my workflow
        - Critical - blocking my use of ClawShield
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
    validations:
      required: false
